main: io.github.spikey84.scepterjavaclaiming.Main
version: 1.0
name: SpikeyClaiming
api-version: 1.13
commands:
  claim:
    usage: /claim
  unclaim:
    usage: /unclaim
  adminclaim:
    aliases:
      - ac
      - aclaim